const data = {
  response_code: {
    version: '1.2',
    termsofService: 'http://frontend.turing.io/projects/wheel-of-fortune.html',
    features: {
      wheel: 1,
      puzzles: 1
    },
  },
  puzzles: {
      puzzle_bank: [
        { category: '2024 Fortress Theme', correct_answer: 'TED Talks', },
        { category: '2025 Fortress Theme', correct_answer: 'Back to the Future', },
        { category: '2026 Fortress Theme', correct_answer: 'National Treasure', },
        { category: '2027 Fortress Theme', correct_answer: 'The Dood Ranch', },
        { category: '2028 Fortress Theme', correct_answer: 'Fake Moon Landing', },
        { category: '2030 Fortress Theme', correct_answer: 'Where\'d You Get Your Incan', },
        { category: '2023 Fortress Theme', correct_answer: 'Afterlife Jam', },
        { category: '2024 Fortress Theme', correct_answer: 'Cocaine Bear', },
        { category: '2025 Fortress Theme', correct_answer: 'SNL Auditions', },
        { category: '2022 Fortress Theme', correct_answer: 'Neurology Resident Room', },
        { category: '2023 Fortress Theme', correct_answer: 'Ann Arbor Pedal Pub', },
        { category: '2024 Fortress Theme', correct_answer: 'Belly Of A Whale', },
        { category: '2021 Fortress Theme', correct_answer: 'Stranger Things', },
        { category: '2022 Fortress Theme', correct_answer: 'The Organ Trail', },
        { category: '2023 Fortress Theme', correct_answer: 'Planet Fitness', },
        { category: '2024 Fortress Theme', correct_answer: 'Chuck E Cheese', },
        { category: '2025 Fortress Theme', correct_answer: 'Wandavision', },
        { category: '2019 Fortress Theme', correct_answer: 'United Clothesline', },
        { category: '2020 Fortress Theme', correct_answer: 'Tibet Town Hall', },
        { category: '2021 Fortress Theme', correct_answer: 'Chernobyl Humane Society', },
        { category: '2022 Fortress Theme', correct_answer: 'Broadway in the Shire', },
        { category: '2018 Fortress Theme', correct_answer: 'Slytherin Common Room', },
        { category: '2019 Fortress Theme', correct_answer: 'Geisha House', },
        { category: '2020 Fortress Theme', correct_answer: 'Sesame Street', },
        { category: '2021 Fortress Theme', correct_answer: 'The Wren Faire', },
        { category: '2022 Fortress Theme', correct_answer: 'Dia De Los Muertos', },
        { category: '2017 Fortress Theme', correct_answer: 'Jurassic Top of the Park', },
        { category: '2018 Fortress Theme', correct_answer: 'Scooby Doo', },
        { category: '2019 Fortress Theme', correct_answer: 'Moulin Rouge', },
        { category: '2020 Fortress Theme', correct_answer: 'Down the Rabbit Hole', },
        { category: '2021 Fortress Theme', correct_answer: 'Box Party', },
        { category: '2016 Fortress Theme', correct_answer: 'Carneval de Venicia', },
        { category: '2017 Fortress Theme', correct_answer: 'Post-Op on Pop', },
        { category: '2018 Fortress Theme', correct_answer: 'Wonka Factory', },
        { category: '2019 Fortress Theme', correct_answer: 'Camleton', },
        { category: '2020 Fortress Theme', correct_answer: 'Civil War USO Show', },
        { category: '2021 Fortress Theme', correct_answer: 'Cromagnon Manor', },
        { category: '2015 Fortress Theme', correct_answer: 'Narnia', },
        { category: '2016 Fortress Theme', correct_answer: 'Montezuma\'s Review', },
        { category: '2017 Fortress Theme', correct_answer: 'Theseus Grocery Run', },
        { category: '2018 Fortress Theme', correct_answer: 'Disney Big Game Hunting', },
        { category: '2019 Fortress Theme', correct_answer: 'The Blue Man Group', },
        { category: '2015 Fortress Theme', correct_answer: 'German Park', },
        { category: '2016 Fortress Theme', correct_answer: 'Hungry Hungry Hip Hop', },
        { category: '2017 Fortress Theme', correct_answer: 'Canadian Duty Free Shop', },
        { category: '2018 Fortress Theme', correct_answer: 'Museums of Michigan', },
        { category: '2019 Fortress Theme', correct_answer: 'The Womb Room', },
        { category: '2020 Fortress Theme', correct_answer: 'Devil Went Up to Michigan', },
        { category: '2013 Fortress Theme', correct_answer: 'Cirque du Soleil', },
        { category: '2014 Fortress Theme', correct_answer: 'Finnegan\'s Wake', },
        { category: '2015 Fortress Theme', correct_answer: 'Fratlantis', },
        { category: '2016 Fortress Theme', correct_answer: 'Game Room of Thrones', },
        { category: '2017 Fortress Theme', correct_answer: 'The Legend of Sleepy Challah', },
        { category: '2018 Fortress Theme', correct_answer: 'Headless Horseman\'s Mitzvah', },
        { category: '2019 Fortress Theme', correct_answer: 'Ellis Island', },
        { category: '2012 Fortress Theme', correct_answer: 'It\'s a Small World', },
        { category: '2013 Fortress Theme', correct_answer: 'Mayan Madness', },
        { category: '2014 Fortress Theme', correct_answer: 'Anarchist\'s Wedding Expo', },
        { category: '2015 Fortress Theme', correct_answer: 'Eastern Blloc Party', },
        { category: '2016 Fortress Theme', correct_answer: 'A Brief History of Love', },
        { category: '2011 Fortress Theme', correct_answer: 'The Salem Meetinghouse', },
        { category: '2012 Fortress Theme', correct_answer: 'The Dry Gulch Saloon', },
        { category: '2013 Fortress Theme', correct_answer: 'Cockfight One and Two', },
        { category: '2014 Fortress Theme', correct_answer: 'Village People Karaoke', },
        { category: '2010 Fortress Theme', correct_answer: 'Beatles at Che Stadium', },
        { category: '2011 Fortress Theme', correct_answer: 'Google Street View', },
        { category: '2012 Fortress Theme', correct_answer: 'Pinnocchio', },
        { category: '2013 Fortress Theme', correct_answer: 'Up the River', },
        { category: '2014 Fortress Theme', correct_answer: 'Pompeii Prom', },
        { category: '2009 Fortress Theme', correct_answer: 'Cafe De Pamplona', },
        { category: '2010 Fortress Theme', correct_answer: 'Werewolf Astronaut', },
        { category: '2011 Fortress Theme', correct_answer: 'The Hobo Jungle', },
        { category: '2012 Fortress Theme', correct_answer: 'Skull and Bones Society', },
        { category: '2008 Fortress Theme', correct_answer: 'Alaskan Fishing Fever', },
        { category: '2009 Fortress Theme', correct_answer: 'Cyborg Wedding', },
        { category: '2010 Fortress Theme', correct_answer: 'Amazing Sea Monkeys', },
        { category: '2011 Fortress Theme', correct_answer: 'Fallout Shelter', },
        { category: '2012 Fortress Theme', correct_answer: 'Mrs O\'Leary\'s Shed', },
        { category: '2013 Fortress Theme', correct_answer: 'Robot Supply and Repair', },
        { category: '2007 Fortress Theme', correct_answer: 'Double Black Diamond', },
        { category: '2008 Fortress Theme', correct_answer: 'The Panic Room', },
        { category: '2006 Fortress Theme', correct_answer: 'Taiwan Best Hot Bar', },
        { category: '2007 Fortress Theme', correct_answer: 'Hall of Unnatural Science', },
        { category: '2008 Fortress Theme', correct_answer: 'The Bird Cage', },
        { category: '2005 Fortress Theme', correct_answer: 'The Bland Ole Opry', },
        { category: '2006 Fortress Theme', correct_answer: 'The Golden Fez', },
        { category: '2004 Fortress Theme', correct_answer: 'Everest Base Camp', },
        { category: '2003 Fortress Theme', correct_answer: 'Nirvana', },
        { category: '2002 Fortress Theme', correct_answer: 'Fortress Gladiators', },
        { category: 'Fortress Party Sticker', correct_answer: 'Like a Fortress Virgin', },
        { category: 'Fortress Party Sticker', correct_answer: 'Don\'t Break the Fort Wall', },
        { category: 'Fortress Party Sticker', correct_answer: 'The Fort Surrounds Us', },
        { category: 'Fortress Party Sticker', correct_answer: 'Maze and Blue', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fjort (Norwegian Fort)', },
        { category: 'Fortress Party Sticker', correct_answer: 'Claustrophilic', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fort Shadowing', },
        { category: 'Fortress Party Sticker', correct_answer: 'Your Sheetin\' Heart', },
        { category: 'Fortress Party Sticker', correct_answer: 'The Fort Authority', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fortitude', },
        { category: 'Fortress Party Sticker', correct_answer: 'Pig in a Blanket', },
        { category: 'Fortress Party Sticker', correct_answer: 'Sally Fort', },
        { category: 'Fortress Party Sticker', correct_answer: 'Safety First', },
        { category: 'Fortress Party Sticker', correct_answer: 'Thread Count Dracula', },
        { category: 'Fortress Party Sticker', correct_answer: 'Riddled With Quilt', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fortissimo', },
        { category: 'Fortress Party Sticker', correct_answer: 'A Fort to Be Reckoned With', },
        { category: 'Fortress Party Sticker', correct_answer: 'Black Sheet of the Family', },
        { category: 'Fortress Party Sticker', correct_answer: 'Tour De Fort', },
        { category: 'Fortress Party Sticker', correct_answer: 'Sheets Going Down', },
        { category: 'Fortress Party Sticker', correct_answer: 'Out of Your Com-Fort Zone', },
        { category: 'Fortress Party Sticker', correct_answer: 'Under Covers Brother', },
        { category: 'Fortress Party Sticker', correct_answer: 'I Rest My Pillow Case', },
        { category: 'Fortress Party Sticker', correct_answer: 'Sheet Faced', },
        { category: 'Fortress Party Sticker', correct_answer: 'Solider of Fortin\'', },
        { category: 'Fortress Party Sticker', correct_answer: 'Walk Like an Egyptian Cotton', },
        { category: 'Fortress Party Sticker', correct_answer: 'Linen and McCartney', },
        { category: 'Fortress Party Sticker', correct_answer: 'Sheet Hits the Fan', },
        { category: 'Fortress Party Sticker', correct_answer: 'And So On and So Fort', },
        { category: 'Fortress Party Sticker', correct_answer: 'Three Sheets to the Wind', },
        { category: 'Fortress Party Sticker', correct_answer: 'Petit Fort', },
        { category: 'Fortress Party Sticker', correct_answer: 'Quilt By Association', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fort-On Hears a Who', },
        { category: 'Fortress Party Sticker', correct_answer: 'Sheet Happens', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fort-Thodox Jew', },
        { category: 'Fortress Party Sticker', correct_answer: 'Model T Fort', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fortin\' Cookie', },
        { category: 'Fortress Party Sticker', correct_answer: 'Out of the Linen Closet', },
        { category: 'Fortress Party Sticker', correct_answer: 'Vladimir Ilyich Linen', },
        { category: 'Fortress Party Sticker', correct_answer: 'Who Forted?', },
        { category: 'Fortress Party Sticker', correct_answer: 'Ape Sheet', },
        { category: 'Fortress Party Sticker', correct_answer: 'Fort-Nite Battle Royale', },
        { category: 'Fortress Party Sticker', correct_answer: 'Lordy Lordy I\'m a Forty', },
        { category: 'Fortress Party Sticker', correct_answer: 'Be Fortful and Multiply', },
      ]
    }
};

module.exports = data;
